version: "3.9"   # optional since v1.27.0
services:
  jupyter:
    build: .
    image: deargle/my-datascience-notebook #My Docker Image
    ports:
      - "10000:8888"
    volumes:
      - .:/home/jovyan/work
